<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DebugType>none</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Core\**" />
      <Compile Remove="Sql\**" />
      <EmbeddedResource Remove="Core\**" />
      <EmbeddedResource Remove="Sql\**" />
      <None Remove="Core\**" />
      <None Remove="Sql\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="BenchConfig.cs" />
      <Compile Remove="CoreBenchmarks.cs" />
      <Compile Remove="EnqueueBenchmarks.cs" />
      <Compile Remove="EnqueueManyBenchmarks.cs" />
      <Compile Remove="ExecutionBenchmarks.cs" />
      <Compile Remove="MemoryBenchmarks.cs" />
      <Compile Remove="ParallelBenchmarks.cs" />
      <Compile Remove="ProcessMemoryBenchmarks.cs" />
      <Compile Remove="ScaleBenchmarks.cs" />
      <Compile Remove="StartupBenchmarks.cs" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Core\CoreBenchmarks.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        
        <!-- WJb -->
        <PackageReference Include="WJb" Version="0.108.1" />

        <!-- Hangfire -->
        <!-- <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" /> -->

        <!-- Quartz -->
        <!-- <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.*" /> -->

        <!-- DI -->
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Enqueue\" />
    </ItemGroup>

</Project>