<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="wwwroot\css\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\!!WJb0622\src\WJb.UI.Blazor\WJb.UI.Blazor.csproj" />
      <ProjectReference Include="..\..\..\!!WJb0622\src\WJb\WJb.csproj" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
    </PropertyGroup>
</Project>
